steps:
  build-pr:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      platforms: linux/amd64
      # Can enable arm64 when moving to mu-javascript-template version >1.8
      # platforms: linux/amd64, linux/arm64
      dry_run: true
when:
  event:
    - pull_request