steps:
  install:
    image: node:14-alpine
    commands:
      - npm ci
  lint:
    image: node:14-alpine
    commands:
      - npm run lint
  build-dry-run:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      platforms: linux/amd64, linux/arm64
      dry_run: true
when:
  event:
    - pull_request
