steps:
  install:
    image: node:14-alpine
    commands:
      - npm i
      # Our lockfile is incompatible with the version of npm used with node:14. The old scripts just
      # `npm i`, so we do that. We should update to a sane node version and change this.
      # - npm ci
  lint:
    image: node:14-alpine
    commands:
      - npm run lint
  build-dry-run:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME}"
      platforms: linux/amd64, linux/arm64
      dry_run: true
when:
  event:
    - pull_request
