steps:
  setup:
    image: semtech/mu-javascript-template:latest
    group: tests
    environment:
      NODE_ENV: "development"
    commands:
      - mkdir -p /usr/src/app/app/node_modules && cp -r ./ /usr/src/app/app
      - cp -r ./ /app/
      - cd /usr/src/app
      - ./prepare-package-json.sh
      - ./transpile-sources.sh
      - npm install
  lint:
    image: semtech/mu-javascript-template:latest
    environment:
      NODE_ENV: "development"
    commands:
      - cd /usr/src/dist/
      - npm run lint:js
  test:
    image: semtech/mu-javascript-template:latest
    environment:
      NODE_ENV: "development"
    commands:
      - cd /usr/src/dist/
      - npm run lint:js
when:
  event:
    - pull_request
