steps:
  install:
    image: node:20-alpine
    commands:
      - npm i
      # Our lockfile is incompatible with the version of npm used with node:14. The old scripts just
      # `npm i`, so we do that. We should update to a sane node version and change this.
      # - npm ci
  lint-js:
    image: node:20-alpine
    group: lint
    commands:
      - npm run lint:js
  tests:
    image: semtech/mu-javascript-template:latest
    working_dir: /app
    group: tests
    commands:
      # complexer then it should be, should be f
      - cd /usr/src/app
      - cp -r /app ./
      - ./prepare-package-json.sh
      - ./transpile-sources.sh
      - cd /usr/src/app/app/
      - npm install
      - npm run test

when:
  event:
    - pull_request
