steps:
  lint-js:
    image: semtech/mu-javascript-template:latest
    image: node:20-alpine
    group: lint
    commands:
      - npm i
      - npm run lint:js
  tests:
    image: semtech/mu-javascript-template:latest
    group: tests
    environment:
      NODE_ENV: 'development'
    commands:
      # complexer then it should be, should be f
      - mkdir -p /usr/src/app/app/node_modules && cp -r ./ /usr/src/app/app
      # merge package uses /app
      - cp -r ./ /app/
      - cd /usr/src/app
      - ./prepare-package-json.sh

      - ./transpile-sources.sh

      - cd /usr/src/dist/
      - npm install
      - cp -R /usr/src/app/helpers/mu /usr/src/dist/node_modules/mu
      - npm run test
when:
  event:
    - pull_request
